export const FETCH_BASE = "FETCH_BASE";
export const FETCH_BOXSHADOW = "FETCH_BOXSHADOW";
export const FETCH_BORDERRADIUS = "FETCH_BORDERRADIUS";
export const FETCH_BORDER = "FETCH_BORDER";

// SNAPSHOTS
export const RESTORE_BASE = "RESTORE_BASE";
export const RESTORE_BOXSHADOW = "RESTORE_BOXSHADOW";
export const RESTORE_BORDERRADIUS = "RESTORE_BORDERRADIUS";
export const RESTORE_BORDER = "RESTORE_BORDER";

// BASE
export const UPDT_BASEWIDTH = "UPDT_BASEWIDTH";
export const UPDT_BASEHEIGHT = "UPDT_BASEHEIGHT";
export const UPDT_BASEMARGIN = "UPDT_BASEMARGIN";
export const UPDT_BASEBGCOLOR = "UPDT_BASEBGCOLOR";

// BOXSHADOW
export const UPDT_BOXSHADOWOFFSETY = "UPDT_BOXSHADOWOFFSETY";
export const UPDT_BOXSHADOWOFFSETX = "UPDT_BOXSHADOWOFFSETX";
export const UPDT_BOXSHADOWBLUR = "UPDT_BOXSHADOWBLUR";
export const UPDT_BOXSHADOWSPREAD = "UPDT_BOXSHADOWSPREAD";
export const UPDT_BOXSHADOWCOLOR = "UPDT_BOXSHADOWCOLOR";
export const UPDT_BOXSHADOWOPACITY = "UPDT_BOXSHADOWOPACITY";
export const UPDT_BOXSHADOWINSET = "UPDT_BOXSHADOWINSET";

// BORDER RADIUS
export const UPDT_BORDERRADIUS_TOPLEFT = "UPDT_BORDERRADIUS_TOPLEFT";
export const UPDT_BORDERRADIUS_TOPRIGHT = "UPDT_BORDERRADIUS_TOPRIGHT";
export const UPDT_BORDERRADIUS_BOTTOMLEFT = "UPDT_BORDERRADIUS_BOTTOMLEFT";
export const UPDT_BORDERRADIUS_BOTTOMRIGHT = "UPDT_BORDERRADIUS_BOTTOMRIGHT";

// BORDERS
export const UPDT_BORDERTOP = "UPDT_BORDERTOP";
export const UPDT_BORDERBOTTOM = "UPDT_BORDERBOTTOM";
export const UPDT_BORDERRIGHT = "UPDT_BORDERRIGHT";
export const UPDT_BORDERLEFT = "UPDT_BORDERLEFT";

// TRANSFORMS
export const UPDT_TRANSLATE = "UPDT_TRANSLATE";
export const UPDT_ROTATE = "UPDT_ROTATE";
export const UPDT_SCALE = "UPDT_SCALE";
export const UPDT_PERSPECTIVE = "UPDT_PERSPECTIVE";
