export const FETCH_BASE = "FETCH_BASE";
export const FETCH_BOXSHADOW = "FETCH_BOXSHADOW";
export const FETCH_BORDERRADIUS = "FETCH_BORDERRADIUS";
export const FETCH_BORDER = "FETCH_BORDER";

export const UPDT_BASE = "UPDT_BASE";
export const UPDT_BOXSHADOW = "UPDT_BOXSHADOW";
export const UPDT_BORDERRADIUS = "UPDT_BORDERRADIUS";
export const UPDT_BORDER = "UPDT_BORDER";

// BASE
export const UPDT_BASEWIDTH = "UPDT_BASEWIDTH";
export const UPDT_BASEHEIGHT = "UPDT_BASEHEIGHT";
export const UPDT_BASEMARGIN = "UPDT_BASEMARGIN";
export const UPDT_BASEBGCOLOR = "UPDT_BASEBGCOLOR";

// BOXSHADOW
export const UPDT_BOXSHADOWOFFSETY = "UPDT_BOXSHADOWOFFSETY";
export const UPDT_BOXSHADOWOFFSETX = "UPDT_BOXSHADOWOFFSETX";
export const UPDT_BOXSHADOWBLUR = "UPDT_BOXSHADOWBLUR";
export const UPDT_BOXSHADOWSPREAD = "UPDT_BOXSHADOWSPREAD";
export const UPDT_BOXSHADOWCOLOR = "UPDT_BOXSHADOWCOLOR";
export const UPDT_BOXSHADOWOPACITY = "UPDT_BOXSHADOWOPACITY";
export const UPDT_BOXSHADOWINSET = "UPDT_BOXSHADOWINSET";

// BORDER RADIUS
// soon

// BORDERS
export const UPDT_BORDERTOP = "UPDT_BORDERTOP";
export const UPDT_BORDERBOTTOM = "UPDT_BORDERBOTTOM";
export const UPDT_BORDERRIGHT = "UPDT_BORDERRIGHT";
export const UPDT_BORDERLEFT = "UPDT_BORDERLEFT";
